populationgenomics/ancestry

- scripts/hail_batch/generate_pca/hgdp_1kg_pca_loadings_generate.py
- scripts/hail_batch/ld_prune/main.py
I missed the fact that ld_prune/main.py requires the 'gnomad' package in the dataproc.hail_dataproc_job function, which is now added in. I also updated the matrix table within the generate_pca/hgdp_1kg_pca_loadings_generate.py script to be the output from ld_prune.
> Update filepath name required packages

- scripts/hail_batch/ld_prune/main.py
After updating the analysis runner to v1.7.0, I added in the option worker_boot_disk_size and set this to 200. I also reduced the number of secondary workers back down to 100, since increasing to 300 doesn't really change things (what matters more is the number of non-preemptible workers).
> Increase worker boot disk size

- scripts/hail_batch/hgdp1kg_tobwgs_pca/README.md
- scripts/hail_batch/hgdp1kg_tobwgs_pca/hgdp_1kg_tob_wgs_pca.py
- scripts/hail_batch/hgdp1kg_tobwgs_pca/main.py
This script combines the HGDP + 1KG dataset with the TOB-WGS dataset, then filters rows to the 90K variants from gnomAD. Once filtered, a PCA is performed.
> Merge HGDP + 1KG dataset with TOB-WGS and PCA

- scripts/hail_batch/ld_prune/README.md
- scripts/hail_batch/ld_prune/hgdp_1kg_ld_prune.py
I filtered to common variants >0.05 (as suggested by Tim Poterba in Zulip) in order to be less memory-intensive.
> Filter to common variants

- scripts/hail_batch/hgdp1kg_tobwgs_pca/README.md
- scripts/hail_batch/hgdp1kg_tobwgs_pca/hgdp_1kg_tob_wgs_pca.py
- scripts/hail_batch/hgdp1kg_tobwgs_pca/main.py
I increased the number of non_preemptible workers to 50 (under the named argumernt 'num_workers', within the hail_dataproc_job function) and removed all preemptible (secondary) workers. I also increased the max age from 10 hours to 24 hours. To ensure the joined TOB-WGS + HGDP/1kG dataset is saved before running the PCA function, I used the `checkpoint` function from hail, and moved this up before the PCA function is called. I also changed the dataset to tob-wgs and the access level to standard (the same command which was run earlier today, but just wasn't updated).
> Increase the number of non_preemptible workers

- scripts/hail_batch/hgdp1kg_tobwgs_pca/hgdp_1kg_tob_wgs_pca.py
Instead of filtering to 50 samples from each dataset (50 from HGDP/1kG and 50 from TOB-WGS), I included all samples. I also added in metadata information back into the matrix table, which will be useful downstream.
> Test all samples, rather than 50 from each dataset

- scripts/hail_batch/hgdp1kg_tobwgs_nfe/README.md
- scripts/hail_batch/hgdp1kg_tobwgs_nfe/hgdp_1kg_tob_wgs_nfe.py
- scripts/hail_batch/hgdp1kg_tobwgs_nfe/main.py
This script performs a PCA on NFE samples only from the combined HGDP/1kG + TOB-WGS dataset. It also filters for variants which are in the gnomad loadings, but not in the TOB-WGS data.
> PCA and variant frequency analsis for NFE samples

- scripts/hail_batch/check_sample_genotype/main.py
I changed the filename in the dataproc.hail_dataproc_job function to `check_genotype.py`, rather than `plot_loadings_nfe.py` (the old filename), which should fix the problem of the analysis runner failing.
> Change filename in dataproc.hail_dataproc_job function

- scripts/hail_batch/check_sample_genotype/main.py
I increased the number of non_preemptible workers to 50 (under the named argumernt 'num_workers', within the hail_dataproc_job function) and removed all preemptible (secondary) workers. This has helped previously due to shuffles causing repetitive failures.
> Increase number of non_preemptible workers

- scripts/hail_batch/check_sample_genotype/check_genotype.py
Previously, I was using extracting the allele frequency for the AMR population from the HGDP/wkG data, which has all avriants. Instead, now I'm only using the HGDP/1kG + TOB-WGS data, which only has the variants included in the TOB-WGS data (this will also make it easier to process for downstream plotting).
> Only get AF from HGDP/1kG + TOB-WGS joined data

- scripts/copy_1kg_hgdp_tob_wgs_pca.sh
I added in a `-r` flag to copy both files, as they have a folder structure. I also added in the `-m` flag, which performs multi-threading. Finally, I changed th e output directorties to mirror the original directories (as suggested by Leo), since this will add in versioning in case I have multiple iterations of these files.
> Add flags to copy

- scripts/hail_batch/hgdp1kg_tobwgs_densify/README.md
- scripts/hail_batch/hgdp1kg_tobwgs_densify/hgdp_1kg_tob_wgs_densify.py
- scripts/hail_batch/hgdp1kg_tobwgs_densify/main.py
I tested the densify function on a small subset of the TOB-WGS data, prior to calling the `lgt_to_gt` function. The AF changes after calling this function, and therefore I'm curious to see whether this has anything to do with the strange AF distribution we were seeing for the TOB-WGS data. This script is intended to get the AF after densifying the data, so that I can see how it affects the AF for the entire dataset.
> Add densify function before calculating AF for TOB-WGS data

- scripts/hail_batch/variant_selection/README.md
- scripts/hail_batch/variant_selection/hgdp_1kg_tob_wgs_variant_selection.py
- scripts/hail_batch/variant_selection/main.py
Since the ~90k variants that were previously chosen by gnomAD were not consistently capturing genotypes for the entire cohort, Loic and I went through the gnomAD v3 marker selection process, but applied to the combined TOB-WGS + HGDP/1kG data. By doing so, this should remove some of the batch effect we're seeing. The aim is to first filter out variants with an AF of 0.1%, but then see how the list changes as we increase this threshold.
> Choose new variants for TOB-WGS + HGDP/1KG dataset

- scripts/hail_batch/hgdp1kg_tobwgs_pca/hgdp_1kg_tob_wgs_pca.py
I densified the TOB-WGS dataset before filtering and converting LGT to GT entries. We've found that densifying the sparse TOB-WGS mt is essential, as it affects downstream results. Densifying is particularly important in this script, where the output is a joined HGDP/1kG + TOB-WGS mt which is used in many downstream analyses. In order to compare the densified and non-densified matrix tables, I renamed the output files in this script by appending `_densified` to the end.
> Densify TOB-WGS data before joining HGDP/1kG and TOB-WGS datasets

- scripts/hail_batch/hgdp1kg_tobwgs_densify/README.md
- scripts/hail_batch/hgdp1kg_tobwgs_densify/hgdp_1kg_tob_wgs_densify.py
- scripts/hail_batch/hgdp1kg_tobwgs_densify/main.py
This script tests the `densify` function on the entire TOB-WGS data. First, the TOB-WGS dataset is densified, then variants are filtered to those within the HGDP/1kG and gnomAD 90k loadings mt. Additionally, I reduced the number of workers from 50 non-preemptible to 20 preemptible workers. The resulting matrix table is checkpointed for downstream use (should be less than 90k).
> Test `densify` function on the full TOB-WGS dataset

- scripts/hail_batch/variant_selection_exploration/hgdp_1kg_tob_wgs_variant_selection_exploration.py
- scripts/hail_batch/variant_selection_exploration/main.py
This script did not successfully finish running after being allocated 5 hours of run time. I checked which operations were taking the longest, and I can rule out `densify` and the `agg.inbreeding` functions. Rather, I think it's either in the row joins or some step within filtering, such as `index_rows`. Since the `print(count_rows())` statements were forcing evaluation after these steps, it was unnecessarily taking too long to complete.
> Remove print statements from variant selection exploration

- scripts/hail_batch/variant_selection_exploration/hgdp_1kg_tob_wgs_variant_selection_exploration.py
Since the filtered matrix table is very large, we want to first explore how many variants we have at different allele frequencies before writing out the filtered variant mt.
> Remove lines to write matrix table

- scripts/hail_batch/hgdp1kg_tobwgs_densify/hgdp_1kg_tob_wgs_densify.py
The previous script failed when adding a line to repartition. After searching through Zulip, it seems as though this may be due to too few partitions.
> Increase number of partitions from 10 to 100

- scripts/hail_batch/hgdp1kg_tobwgs_densify/hgdp_1kg_tob_wgs_densify.py
I increased the number of rows from 100 to 1000, since the previous script failed due to memory issues. Oddly, since the matrix table should be less than 90k rows, 100 partitions does seem sufficient, and therefore I added in a `count_rows()` statement to do a quick sanity check on how big the matrix table actually is. I also cached the tob_wgs data before printing the number of rows, so that I don't recompute the entire list of operations for printing and for saving the mt.
> Increase number of partitions and check number of rows from filtered mt

- scripts/hail_batch/variant_selection/README.md
- scripts/hail_batch/variant_selection/hgdp_1kg_tob_wgs_variant_selection.py
- scripts/hail_batch/variant_selection/main.py
After speaking with Loic this morning and looking at the histogram plot output from `hgdp_1kg_tob_wgs_variant_selection_exploration.py`, we decided that increasing the variant allele frequency to 0.01, rather than 0.001, would reduce many of the variants while still keeping rare variants in the analysis. We also found that ld_prune removes around 90% of the variants (at least on the subset of 1M variants that we tested on). Therefore, to retain around 100K variants, I've sub-sampled the remaining variants after filtering to 1M, before LD-pruning. 
I tested this script first on the TOB-WGS data in the `test` bucket, which finished successfully. I've also taken the same parameters for the `dataproc.hail_dataproc_job` from the `ancestry/scripts/hail_batch/variant_selection_exploration/main.py …
>  Change AF to 1% and subsample to 1M variants before pruning

- scripts/hail_batch/variant_selection/main.py
My script failed with an error message of "File could only be replicated to 0 nodes instead of minReplication (=1)", which is likely due to HDFS running out of space. The GCP metrics explorer also confirmed that there was not enough HDFS space, so I increased this to 200.
> Increase HDFS space by increasing worker_boot_disk_size

- scripts/hail_batch/hgdp1kg_tobwgs_densified_pca/main.py
I changed the `main.py` script for the wrong folder (variant_selection rather than hgdp1kg_tobwgs_densified_pca). As stated in the PR cf2fd4c, my script failed with the error "File could only be replicated to 0 nodes instead of minReplication (=1)", and the GCP metrics explorer confirmed this was due to running out of HDFS space. I now increased this to 200.
> Increase hdfs space for densified tob-wgs script

- scripts/hail_batch/variant_selection/hgdp_1kg_tob_wgs_variant_selection.py
- scripts/hail_batch/variant_selection/main.py
I repartitioned the `hgdp1kg_tobwgs_joined` matrix table to 100 partitions, as it is heavily filtered. I also incorrectly added `worker_boot_disk_size=200` in the `dataproc.hail_dataproc_job` function, and therefore am removing this.
> Repartition `hgdp1kg_tobwgs_joined` mt and remove worker_boot_disk_size

- scripts/hail_batch/variant_selection/README.md
- scripts/hail_batch/variant_selection/main.py
My last script failed with a [timeout error](https://batch.hail.populationgenomics.org.au/batches/2742/jobs/2), which is likely due to the repartitioning step of my code. Since I'm now repartitioning the`hgdp1kg_tobwgs_joined` matrix table using a shuffle, as suggested by [Tim Poterba on Zulip](https://hail.zulipchat.com/#narrow/stream/123010-Hail-0.2E2.20support/topic/How.20to.20choose.20number.20of.20partitions.20when.20repartitioning), I want to test whether this can be solved by using primary workers, rather than secondary workers. I chose 50, but this might need to be scaled down.
> Replace secondary workers with primary workers

- scripts/plotting/hgdp_1kg_tob_wgs_pop_pca_densified_all_samples/hgdp_1kg_tob_wgs_plot_pca_all_samples.py
Generate PCA plots of all combined HGDP/1kG + TOB-WGS samples and include HTML output, as well as png output in the `web` bucket. HTML output is useful, as it allows for viewing sample names and attributes of individual points within the PCA.
> Generate PCA plots including html output

- scripts/plotting/hgdp_1kg_tob_wgs_pop_pca_densified_nfe_loadings/README.md
- scripts/plotting/hgdp_1kg_tob_wgs_pop_pca_densified_nfe_loadings/hgdp_1kg_tob_wgs_plot_loadings_nfe.py
I accidentally put the plotting command outside of the for loop, so now it's contained inside and should save every single pc loadings plot, rather than just the one. I've also updated the path in the README file, whie was `gs://cpg-tob-wgs-main` rather than `gs://cpg-tob-wgs-main-web`
> Add plotting command inside of for loop

- scripts/hail_batch/variant_selection/hgdp_1kg_tob_wgs_variant_selection.py
Since our previous script failed with a timeout, I'm testing repartitioning using 1000 partitions. I've alse saved the tmp file to the `cpg-tob-wgs-main-tmp` bucket.
> Increase the number of partitions from 100 to 1000

- scripts/plotting/reprocessed_gatk4_samples_pca/project_reprocessed_gatk4_samples.py
I can't actually see the points in my plot because the circle glyphs are not opaque. I tried finding a simple way to do this using `hl.plot.scatter()`, but unfortunately I couldn't find anything helpful within the documentation. The best solution I could find is setting up a basic plotting space using `plot`, then projecting the glyphs onto that space using the coordinates from the pca scores (as done originally, just with `hl.plot.scatter`).
> Increase glyph transparency when plotting

- scripts/plotting/hgdp_1kg_tob_wgs_pop_pca_densified_nfe_loadings/hgdp_1kg_tob_wgs_plot_loadings_nfe.py
Negative log10 p-values from the original manhattan plot code were still in the hover fields of my manhattan plot, so I changed these to the raw p-values. I also deleted `SCORES`, `EIGENVALUES`, and the HGDP/1kG + TOB/WGS matrix table, as none of these are needed for the loadings plot.
> Change labels of hover fields

- scripts/hail_batch/variant_selection/hgdp_1kg_tob_wgs_variant_selection.py
- scripts/hail_batch/variant_selection/main.py
I removed the temporary path and checkpoint and instead repartitioned using the same method we used in `hgdp_1kg_tob_wgs_densify.py`, which completed successfully.  I've also printed out the number of rows in the pruned variant table, so that we get a better idea of where the code is breaking if it fails.
> Remove tmp file and repartition as in `hgdp_1kg_tob_wgs_densify.py`

- scripts/plotting/project_snp_chip_data/project_snp_chip_data.py
The union_scores table needs to get calculated in a for-loop over every iteration. My previous script failed due to a timeout, and I believe it is due to unnecessarily performing the calculation in the for-loop each time.
> Persist union scores

- scripts/hail_batch/variant_selection/hgdp_1kg_tob_wgs_variant_selection.py
My script [failed ](https://batch.hail.populationgenomics.org.au/batches/3052/jobs/2) with an error `Cannot change storage level of an RDD after it was already assigned a level at org.apache.spark.rdd.RDD.persist(RDD.scala:170)`. I searched what this error may be due to and it looks like it might be caused by persisting the `pruned_variant_table` into memory, as it may already be persisted into memory (as suggested [here](https://stackoverflow.com/questions/37750545/cannot-change-storage-level-of-rdd)). I also got the warning `WARN: over 400,000 edges are in the graph; maximal_independent_set may run out of memory`, suggesting that I just have too many input variants into `ld_prune`. Although the total output variants will be less, I'm curious if ld_prune can actually handle so many …
> Reduce number of input variants for LD prune and remove caching

- scripts/hail_batch/variant_selection/hgdp_1kg_tob_wgs_variant_selection.py
My script failed again, even after reducing the number of variants into ld-prune and trying several differnet ways to save my reprtitioned table. To test whether this issue is due to repartitioning (which it likely is), I'm omitting the repartitioning step, but will ask in Zulip what the best way forward is for repartitioning tables after heavy filtering.
> Delete repartitioning step after ld-prune

- scripts/hail_batch/snp_chip_generate_pca/snp_chip_generate_pca.py
Although the files in the `test` bucket have `GT` fields, the (latest) file in `main` requires converting `LGT` to `GT`. You can see the full error [here](https://batch.hail.populationgenomics.org.au/batches/3102/jobs/2).
> Convert `LGT` field to `GT`

- scripts/hail_batch/snp_chip_generate_pca/snp_chip_generate_pca.py
The ordering of `select_entries` and `select_cols` seems to matter when assigning `lgt_to_gt(tob_wgs.LGT, tob_wgs.LA)` to `GT` (the error can be seen [here](https://batch.hail.populationgenomics.org.au/batches/3104/jobs/2)). I've now rearranged these and tested the whole script on `gs://cpg-tob-wgs-test/mt/v2-raw.mt/` instead of `gs://cpg-tob-wgs-test/mt/v3.mt/`, since the `LGT` field is present in the former file.
> Reorder `select_entries` and `select_cols` fields

- scripts/hail_batch/snp_chip_generate_pca/snp_chip_generate_pca.py
I appended 'snp_chip' as a suffix to the TOB SNP-chip dataset, so that I can differentiate samples when I plot. I also tested this and saved a subset of the data to the `test` bucket
> Differentiate dataset names

- scripts/hail_batch/snp_chip_generate_pca/README.md
- scripts/hail_batch/snp_chip_generate_pca/main.py
- scripts/hail_batch/snp_chip_generate_pca/snp_chip_generate_pca.py
I updated the way my output is constructed by using `output_path(filename)` rather than `f'{output}/filename`. I also updated the init script to `install_common` and did a test run beforehand to make sure everything is working after the new analysis runner update.
> Update output paths after updated analysis runner version

- scripts/plotting/tob_wgs_snp_chip_plot_pca/plot_pca_tob_wgs_snp_chip_datasets.py
In my previous script, I plotted samples highlighted by their sequencing technology (whole genome sequence or SNP-chip, as seen [here](https://main-web.populationgenomics.org.au/tob-wgs/tob_wgs_snp_chip_pca/v0/pc1.html)), however it was  difficult to make out which samples are exclusively SNP-chip, which are exclusively WGS, and which are both. This script plots this information in a scatter plot and also outputs an html file with sample information and whether or not it is exclusively a WGS sample, SNP-chip sample, or present in both.
> Get information on technology of samples and overlap

- scripts/plotting/variant_selection_qc_histogram/variant_selection_qc_histogram.py
My [variant selection script](https://main-web.populationgenomics.org.au/tob-wgs/tob_wgs_hgdp_1kg_variant_selection/v0/variant_selection_histogram.html) worked! However, the bins are a bit too large (the default is 10 bins), so I want to see the allele frequency at a more granular level. I've therefore increased the bin size to 100.
> Increase bin size

- scripts/hail_batch/snp_chip_pca_sanity_check/README.md
- scripts/hail_batch/snp_chip_pca_sanity_check/main.py
- scripts/hail_batch/snp_chip_pca_sanity_check/snp_chip_only_generate_pca.py
Generate PCA of SNP chip samples only after [successfully running](https://batch.hail.populationgenomics.org.au/batches/3430/jobs/2) in the`test` bucket.
> Perform PCA on SNP-chip data only

- scripts/hail_batch/project_wgs_onto_snp_chip_pca/README.md
- scripts/hail_batch/project_wgs_onto_snp_chip_pca/main.py
- scripts/hail_batch/project_wgs_onto_snp_chip_pca/project_wgs_samples_onto_snp_chip.py
In my previous script plotting WGS + SNP-chip samples (`tob_wgs_snp_chip_plot_pca/plot_pca_tob_wgs_snp_chip_datasets.py`), it was clear that SNP-chip data which was not present in the WGS data was under-represented, therefore resulting in less spread than the other samples. To remove this effect, I've computed and plotted a PCA of the SNP-chip data only and then projected the WGS samples onto it. Unfortunately, I could not expand the rows as per Loic's '[Concordance analysis between a sparse and a dense MatrixTable'](https://nbviewer.jupyter.org/github/populationgenomics/tob-deepdive/blob/main/ConcordanceAnalysis.ipynb) pipeline, since the samples do not match between the WGS data and the TOB-WGS data (a dependency of `union_rows`).
> Project TOB-WGS samples onto SNP-chip PCA

- scripts/hail_batch/increase_snp_chip_partitions/README.md
- scripts/hail_batch/increase_snp_chip_partitions/increase_snp_chip_partitions.py
- scripts/hail_batch/increase_snp_chip_partitions/main.py
Since the SNP-chip matrix table currently only has one partition, this becomes problematic when intersecting with a large matrix table with many partitions. I've therefore increased the total number of partitions in order to better parallelise the data.
> Increase the number of partitions in SNP-chip dataset to 100 

- scripts/hail_batch/project_wgs_onto_snp_chip_pca/README.md
- scripts/hail_batch/project_wgs_onto_snp_chip_pca/project_wgs_samples_onto_snp_chip.py
My initial script didn't successfully complete after 12 hours of runtime, and this is likely due to the SNP-chip matrix table only having one partition (i.e., relying on one worker after intersecting with the much larger TOB-WGS dataset). I'm therefore re-testing this script after increasing the number of partitions in the SNP-chip dataset (done [here](https://github.com/populationgenomics/ancestry/blob/main/scripts/hail_batch/increase_snp_chip_partitions/increase_snp_chip_partitions.py).
> Project WGS data onto repartitioned mt

- scripts/hail_batch/project_wgs_onto_snp_chip_pca/project_wgs_samples_onto_snp_chip.py
I've updated the file name to use the SNP-chip matrix table which was repartitioned using 1000 partitions, rather than 100 (as done and described [here](https://github.com/populationgenomics/ancestry/tree/main/scripts/hail_batch/increase_snp_chip_partitions)).
> Update file name to the newly-partitioned mt

- scripts/hail_batch/hgdp1kg_tobwgs_densified_pca_new_variants/README.md
- scripts/hail_batch/hgdp1kg_tobwgs_densified_pca_new_variants/hgdp_1kg_tob_wgs_densified_pca_new_variants.py
- scripts/hail_batch/hgdp1kg_tobwgs_densified_pca_new_variants/main.py
Perform PCA on newly-selected variants, chosen for the combined TOB-WGS + HGDP/1KG dataset (based off of the same filtering criteria as gnomAD v2.1,but not limited to exonic regions). Since I'm also interested in performing a PCA on NFE samples only, I'm also saving the combined TOB-WGS + HGDP/1KG matrix table, which is a dependency for that analysis.
> Pca new variants

- scripts/hail_batch/project_wgs_onto_snp_chip_pca/main.py
After further increasing the SNP-chip dataset to 1000 partitions, it still [failed](https://batch.hail.populationgenomics.org.au/batches/3601/jobs/2) with a memory error. One [suggestion](https://discuss.hail.is/t/pca-job-aborted-from-sparkexception/1433) is using n1-highmem worker nodes instead of n1-standard worker nodes. I've therefore added this as an argument in the `main.py` file within the `hail_dataproc_job` function.
> Add highmem worker machine type

- scripts/plotting/hgdp_1kg_tob_wgs_pca_new_variants/main.py
- scripts/plotting/hgdp_1kg_tob_wgs_pca_new_variants/plot_pca_and_loadings.py
My script was nearly finished, but failed after one of the last steps (plotting the loadings, which was half way through). I've now increased the run time from one to two hours, which should be sufficient. I also noticed that my metadata/continental populations were not properly matched to the scores table. I've now matched them using `hgdp1kg_tobwgs.cols()[scores.s].hgdp_1kg_metadata.population_inference.pop`
> Increase run time and match metadata to samplenames

- scripts/hail_batch/increase_snp_chip_partitions/increase_snp_chip_partitions.py
After another failed script from `project_wgs_onto_snp_chip_pca/project_wgs_samples_onto_snp_chip.py` (which is dependent on the output from this script), I want to try increasing the number of partitions to 10k to more closely mirror the number of partitions from `snp_chip_generate_pca/snp_chip_generate_pca.py`, which runs the same analysis but completed successfully.
> Increase number of partitions to 10k

- scripts/hail_batch/project_wgs_onto_snp_chip_pca/main.py
- scripts/hail_batch/project_wgs_onto_snp_chip_pca/project_wgs_samples_onto_snp_chip.py
Update preemptible workers to non-preemptible workers and add in newly-partitioned snp-chip file, which now has 10k partitions (from `increase_snp_chip_partitions/increase_snp_chip_partitions.py`).
> Add 20 non-preemptible workers and update snp-chip file

- scripts/hail_batch/hgdp1kg_tobwgs_pca_pop_densified_new_variants/README.md
- scripts/hail_batch/hgdp1kg_tobwgs_pca_pop_densified_new_variants/hgdp_1kg_tob_wgs_pop_pca_densified.py
- scripts/hail_batch/hgdp1kg_tobwgs_pca_pop_densified_new_variants/main.py
Perform PCA on TOB-WGS + NFE samples only using the newly-selected variants which were chosen specifically for the combined TOB-WGS + HGDP/1KG datasets.
> Perform PCA on NFE subset, using new variants

- scripts/hail_batch/project_wgs_onto_snp_chip_pca/project_wgs_samples_onto_snp_chip.py
My script failed with the [error](https://batch.hail.populationgenomics.org.au/batches/3755/jobs/2) 
```
eigenvalues = eigenvalues.checkpoint(eigenvalues_path)
AttributeError: 'list' object has no attribute 'checkpoint'
```
so I have removed this checkpoint. Furthermore, checkpointing the `loadings` and `scores` tables already provides information on which stage the script is at.
> Remove checkpoint for eigenvalues list

- scripts/hail_batch/hgdp1kg_tobwgs_pca_pop_densified_new_variants/main.py
My script failed with the [error ](https://batch.hail.populationgenomics.org.au/batches/3753/jobs/2): 
```
RemoteException: File /tmp/write-table-concatenated-g9Xt6exvKdKQqbtVx72sar/_temporary/0/_temporary/attempt_202107280834516532796308026131585_0735_m_000063_19/part-00063 could only be written to 0 of the 1 minReplication nodes. There are 2 datanode(s) running and 2 node(s) are excluded in this operation.
```
Which is likely due to [running out of disk space](https://hail.zulipchat.com/#narrow/stream/123010-Hail-0.2E2.20support/topic/could.20only.20be.20written.20to.200.20of.20the.201.20minReplication.20nodes). 
This was confirmed in the metric explorer:
> Increase HDFS space

- scripts/plotting/hgdp_1kg_tob_wgs_pop_pca_new_variants_nfe/hgdp_1kg_tob_wgs_plot_pca_nfe.py
Hail has a `collect_all` function, where it downsamples before plotting. This must be set as 'True' if all samples are to be shown in the plot
> Add `collect_all=True` in `hl.plot.scatter` function

- scripts/hail_batch/hgdp1kg_tobwgs_pca_nfe_new_variants_no_outliers/README.md
- scripts/hail_batch/hgdp1kg_tobwgs_pca_nfe_new_variants_no_outliers/hgdp_1kg_tob_wgs_nfe_pca_no_outliers.py
- scripts/hail_batch/hgdp1kg_tobwgs_pca_nfe_new_variants_no_outliers/main.py
This script performs PCA for nfe samples on the densified TOB-WGS matrix table, filtered for variants selected specifically for the combined TOB-WGS + HGDP/1KG datasets. Two outlier samples, which were generated in `hgdp_1kg_tob_wgs_pop_pca_new_variants_nfe/hgdp_1kg_tob_wgs_plot_pca_nfe.py`, have been removed in order to see more clear clustering between samples.
> Generate PCA on NFE samples with outliers removed

- scripts/plotting/hgdp_1kg_tob_wgs_pca_new_variants_nfe_no_outliers/README.md
- scripts/plotting/hgdp_1kg_tob_wgs_pca_new_variants_nfe_no_outliers/hgdp_1kg_tob_wgs_plot_pca_nfe.py
- scripts/plotting/hgdp_1kg_tob_wgs_pca_new_variants_nfe_no_outliers/main.py
This script is exactly the same as `hgdp_1kg_tob_wgs_pop_pca_new_variants_nfe/hgdp_1kg_tob_wgs_plot_pca_nfe.py`, but removes two outlier samples which skew the PCA plot and make clustering hard to interpret across samples.
> Plot pca of NFE samples, removing two outlier samples

- scripts/plotting/hgdp_1kg_tob_wgs_pca_new_variants_nfe_no_outliers/hgdp_1kg_tob_wgs_plot_pca_nfe.py
In my previous PCA plot of NFE samples, it's hard to make out where the TOB-WGS samples are (see https://main-web.populationgenomics.org.au/tob-wgs/tob_wgs_hgdp_1kg_nfe_pca_new_variants/v1/subpopulation_pc1.html). I've therefore increased the alpha/transparency, and also tried rearranging the subpopulations so TOB-WGS is on top.
> Add transparency to glyphs in PCA plot

- scripts/hail_batch/hgdp1kg_tobwgs_pca_nfe_new_variants_no_outliers/hgdp_1kg_tob_wgs_nfe_pca_no_outliers.py
Remove outlier TOB1126 to show spread out NFE samples more clearly. We found this sample to be a clear outlier, as shown in the PCA plot here: https://main-web.populationgenomics.org.au/tob-wgs/tob_wgs_hgdp_1kg_nfe_pca_new_variants/v2/study_pc1.html.
> Remove outlier TOB1126

- scripts/plotting/hgdp_1kg_tob_wgs_pca_new_variants_nfe_no_outliers/hgdp_1kg_tob_wgs_plot_pca_nfe.py
This plots the output from `hgdp1kg_tobwgs_pca_nfe_new_variants_no_outliers/
hgdp_1kg_tob_wgs_nfe_pca_no_outliers.py`, which was generated after removing three outliers: TOB1734, TOB1714, and TOB1126.
> Update paths for PCA, conducted after removing sample outliers

- scripts/hail_batch/hgdp1kg_tobwgs_pca_nfe_new_variants_no_outliers/hgdp_1kg_tob_wgs_nfe_pca_no_outliers.py
Remove samples TOB1653 and TOB1668, which were found to be outliers in [PC2](https://main-web.populationgenomics.org.au/tob-wgs/tob_wgs_hgdp_1kg_nfe_pca_new_variants/v3/study_pc2.html) and [PC3](https://main-web.populationgenomics.org.au/tob-wgs/tob_wgs_hgdp_1kg_nfe_pca_new_variants/v3/study_pc3.html), respectively.
> Remove samples TOB1653 and TOB1668

- scripts/plotting/hgdp_1kg_tob_wgs_pca_new_variants_nfe_no_outliers/hgdp_1kg_tob_wgs_plot_pca_nfe.py
This plots the output from `hgdp1kg_tobwgs_pca_nfe_new_variants_no_outliers/hgdp_1kg_tob_wgs_nfe_pca_no_outliers.py`, which has samples TOB1734, TOB1714, TOB1126, TOB1653, and TOB1668 removed.
> Plot PCA with outliers removed

- scripts/plotting/hgdp_1kg_tob_wgs_pca_new_variants_nfe_no_outliers/hgdp_1kg_tob_wgs_plot_pca_nfe.py
This plots the output from `hgdp1kg_tobwgs_pca_nfe_new_variants_no_outliers/hgdp_1kg_tob_wgs_nfe_pca_no_outliers.py`, which is a PCA with outlier samples and related samples removed. In total, 87 samples were removed, which seems like a lot. However, 662 samples were removed from the HGDP/1kG dataset by gnomAD since they were found to be second-degree related or closer (see https://gnomad.broadinstitute.org/news/2020-10-gnomad-v3-1-new-content-methods-annotations-and-data-availability/#the-gnomad-hgdp-and-1000-genomes-callset). Since I'll be using `pc_relate` in the future for QC, I think it's useful to see how it performs. However, I've also compared the filtered, related samples to the gnomAD metadata table which states whether samples were included in gnomAD v3.1 or not.
> Plot pca with related samples removed

- scripts/hail_batch/hgdp1kg_tobwgs_nfe_pc_relate/README.md
- scripts/hail_batch/hgdp1kg_tobwgs_nfe_pc_relate/hgdp_1kg_tob_wgs_nfe_pc_relate.py
- scripts/hail_batch/hgdp1kg_tobwgs_nfe_pc_relate/main.py
I want to investigate the kinship estimates for outlier samples that are known to be related (see [HG01696](https://www.internationalgenome.org/data-portal/sample/HG01696) and [HG01629](https://www.internationalgenome.org/data-portal/sample/HG01629)), as shown by previous[ PCA plots](https://main-web.populationgenomics.org.au/tob-wgs/tob_wgs_hgdp_1kg_nfe_pca_new_variants/v6/subpopulation_pc1.html). It could be that the estimates are just below the threshold, and therefore the minimum relatedness threshold may need to be adjusted. The output from `pc_relate` is a very large dataframe, since it gets the relatedness score for each sample (i) compared to every other sample (j). Therefore, I'm just plotting the output of known outliers for now.
> Output kinship estimates for related outlier samples in PCA plot

- scripts/hail_batch/hgdp1kg_tobwgs_pca_nfe_new_variants_no_outliers/hgdp_1kg_tob_wgs_nfe_pca_no_outliers.py
After adjusting different parameters in `pc_relate`, I couldn't seem to figure out why two samples---HG01696 and HG01629---are not removed. Digging into why this is happening will be important for future instances using the method, but until then, the metadata table within the HGDP/1kG subset specifies which samples were removed from the gnomAD release due to being related (at the second degree or closer). I've gone ahead and filtered out related samples using this method instead.
> Remove samples which are not included in the gnomAD v3.1 release

- scripts/plotting/hgdp_1kg_tob_wgs_pca_new_variants_nfe_no_outliers/hgdp_1kg_tob_wgs_plot_pca_nfe.py
This plots the output from `hgdp1kg_tobwgs_pca_nfe_new_variants_no_outliers/hgdp_1kg_tob_wgs_nfe_pca_no_outliers.py`. This PCA was updated to remove all samples which are excluded from the gnomAD v3.1 release due to being related at the second degree or closer.
> Plot PCA after removing samples which are not in the gnomAD v3.1 release

- scripts/plotting/hgdp_1kg_tob_wgs_pca_nfe_loadings_no_outliers/hgdp_1kg_tob_wgs_plot_loadings_nfe_no_outliers.py
- scripts/plotting/hgdp_1kg_tob_wgs_pca_nfe_loadings_no_outliers/main.py
This updated loadings plot takes a GTF file to annotate every variant with its gene name. Additionally, I've included information for samples which are heterozygous or homozygous alternate alleles, giving more information on pc loadings which are driven by singletons.
> Update loadings plot to include gene names, identify samples driving singletons

- scripts/plotting/hgdp_1kg_tob_wgs_pca_nfe_loadings_no_outliers/hgdp_1kg_tob_wgs_plot_loadings_nfe_no_outliers.py
I had '1' in my loop rather than a variable, so PC1 was plotted each time 🤦‍♀️ I've now updated it
> Fix manhattan plot loop so that it ierates over all samples

- scripts/plotting/hgdp_1kg_tob_wgs_pca_nfe_loadings_no_outliers/hgdp_1kg_tob_wgs_plot_loadings_nfe_no_outliers.py
- scripts/plotting/hgdp_1kg_tob_wgs_pca_nfe_loadings_no_outliers/main.py
The significant_variants output is taking too long to generate without any workers. I've added 20 preemptible/secondary workers, which should speed this up. I've also added in the `hadoop_exists`function so that files that have already been generated do not need to be rerun.
> Increase workers

- scripts/hail_batch/hgdp1kg_tobwgs_pca_nfe_new_variants_no_outliers/hgdp_1kg_tob_wgs_nfe_pca_no_outliers.py
From exploring the PCA plots from `hgdp_1kg_tob_wgs_pca_new_variants_nfe_no_outliers/hgdp_1kg_tob_wgs_plot_pca_nfe.py`, it looks like three samples---TOB1681, TOB1116, and TOB1107---are ancestry outliers and driving variation in the first 5 PCs. I've now removed these.
> Remove three additional outlier TOB NFE samples, who are ancestry outliers

- scripts/hail_batch/hgdp1kg_tobwgs_pca_nfe_new_variants_no_outliers/hgdp_1kg_tob_wgs_nfe_pca_no_outliers.py
Remove 8 additional outlier samples, as shown in [PC3](https://main-web.populationgenomics.org.au/tob-wgs/tob_wgs_hgdp_1kg_nfe_pca_new_variants/v11/subpopulation_pc3.html)-[PC10](https://main-web.populationgenomics.org.au/tob-wgs/tob_wgs_hgdp_1kg_nfe_pca_new_variants/v11/subpopulation_pc10.html) of the last PCA run.
> Remove 8 additional outlier samples

- scripts/plotting/hgdp_1kg_tob_wgs_pca_new_variants_nfe_no_outliers/hgdp_1kg_tob_wgs_plot_pca_nfe.py
- scripts/plotting/hgdp_1kg_tob_wgs_pca_nfe_loadings_no_outliers/hgdp_1kg_tob_wgs_plot_loadings_nfe_no_outliers.py
I updated the paths to plot the new PCA output from `hgdp1kg_tobwgs_pca_nfe_new_variants_no_outliers/hgdp_1kg_tob_wgs_nfe_pca_no_outliers.py`, which removed 8 additional PCA outliers.
> Update path to most recent PCA output

- scripts/plotting/hgdp1kg_tobwgs_pc_relate_unpruned/hgdp_1kg_tob_wgs_related_samples.py
Previously, I exported csv files as all individuals and their relatedness scores, which was far too large. I'm now filtering down to only individuals who are related, which greatly reduces the size of the file.
> Filter table to just related samples

- scripts/hail_batch/data_transfer/move_tob_wgs_plink.sh
My script [failed](https://batch.hail.populationgenomics.org.au/batches/5448/jobs/1) with the error:
```File "move_tob_wgs_plink.sh", line 5
gsutil -m -cp -r "gs://cpg-tob-wgs-main/tob_wgs_plink/v0/*" "gs://cpg-tob-wgs-shared-jpowell/mt/plink/"
^
SyntaxError: invalid syntax```
I've now removed the asterisk.
> Remove asterisk from command

- scripts/reports/relatedness_method_test/correlation_pc_relate_king_report.Rmd
After digging into my data a bit more, I realised that while I filtered to samples which were only present in both datasets, some of the samples which were flagged as related don't actually have their related pair in my dataset. Therefore, the numbers were unfairly skewed towards false negatives. I've now fixed this by filtering on the basis of a sample having a related pair in the dataset, then filtering to samples which are present in both datasets.
> Update RMD file after adjusting for samples not in dataset

- scripts/hail_batch/eqtl_hail_batch/generate_eqtl_spearman.py
This worked for me. 
1. Note `j.env('HAIL_QUERY_BACKEND', 'local')` - I set the variable specifically for this job, because that's the job where `hl.init()` is called. 
2. Note that for temporary files (like spearman_df.csv) I use the local filesystem instead of the bucket (to get around `No FileSystem for scheme "gs"` issue like here https://batch.hail.populationgenomics.org.au/batches/6485/jobs/1)
> Use HAIL_QUERY_BACKEND=local for the job

- scripts/plotting/scree_plot_tob_wgs/README.md
- scripts/plotting/scree_plot_tob_wgs/main.py
- scripts/plotting/scree_plot_tob_wgs/tob_wgs_scree_plot.py
Make scree plot of the TOB-WGS + NFE samples (from HGDP + 1kg dataset) in order to identify the number of PCs to use in the association script LM. Output is from `hail_batch/final_tob_batch_pca/generate_pca_no_outliers.py`
> Make scree plot of TOB-WGS data
