scripts/hail_batch/HGDP_1KG_PCALoadingsGenerate.py
scripts/hail_batch/README.md
scripts/hail_batch/hgdp_1kg_pca_loadings_generate.py
scripts/hail_batch/main.py

Scripts to generate PCA loadings, using the analysis runner.

Add files for the analysis runner.

---

scripts/hail_batch/main.py

Change filename

---

scripts/hail_batch/generate_pca_10k_random/README.md
scripts/hail_batch/generate_pca_10k_random/hgdp_1kg_pca_10k_random.py
scripts/hail_batch/generate_pca_10k_random/main.py

I only chose high-quality variants, i.e., variants with a call rate >= 0.99. Hail also has a downsampling function, which I used to randomly subsample to 10k rows.

Add in new scripts for running a PCA on 10k randomly-selected rows.

---

scripts/hail_batch/ld_prune/main.py

Increase number of secondary workers from 150 to 300.

Increase number of secondary workers

---

scripts/hail_batch/generate_pca_10k_random/README.md
scripts/hail_batch/generate_pca_10k_random/hgdp_1kg_pca_10k_random.py

Since the previous script worked, I increased the dataset from 100 to 3942 (the entire dataset). I also added in a random seed to the downsampled matrix (for reproducibility) and saved it for downstream use.

Increase samples from 100 to entire dataset

---

scripts/hail_batch/check_sample_genotype/README.md
scripts/hail_batch/check_sample_genotype/check_genotype.py
scripts/hail_batch/check_sample_genotype/main.py

I got a very strange distribution when looking at the TOB-WGS allele frequency and am therefore doing some sanity checks to ensure no mistakes were made along the way. This includes: 1) spot-checking three TOB-WGS samples for their genotype and comparing this to the results Peter got and 2) calling allele frequencies on one population (here I randomly selected "amr") so that I can compare this to the previously-called gnomAD allele frequencies.

QC metrics to undertsand AF distribution plots

---

scripts/hail_batch/check_sample_genotype/README.md

The previous run of the analysis runner failed, so hopefully changing the access level should fix it.

Change access level to standard

---

scripts/hail_batch/check_sample_genotype/check_genotype.py
scripts/hail_batch/check_sample_genotype/main.py

Perhaps one reason why the analaysis runner isn't working is due to feather incorrect;y being loaded, rather than pyarrow.

Change 'feather' module to 'pyarrow' module in Python packages.

---

scripts/hail_batch/check_sample_genotype/check_genotype.py
scripts/hail_batch/check_sample_genotype/main.py

After unsuccessfully trying to save the output files, I'm saving output at the most basic level and outputing them as .tsv files. I also changed the number of workers from primary to secondary.

Save data as 'tsv' rather than 'feather'

---

scripts/hail_batch/variant_selection_exploration/README.md
scripts/hail_batch/variant_selection_exploration/hgdp_1kg_tob_wgs_variant_selection_exploration.py
scripts/hail_batch/variant_selection_exploration/main.py

Since my variant selection script uses more variants than we have previously used, and therefore will be compuationally expensive for the following LD-pruning step, this script is intended to explore how many variants we have at different AF thresholds.

Explore possible AF cutoffs for variant selection script

---

scripts/hail_batch/variant_selection_exploration/README.md
scripts/hail_batch/variant_selection_exploration/hgdp_1kg_tob_wgs_variant_selection_exploration.py

The TOB-WGS path in the `main` bucket was updated, so I needed to change that. I also updated `web` to `main-web` after the new bucket names.

Update TOB-WGS path

---

scripts/hail_batch/hgdp1kg_tobwgs_densify/hgdp_1kg_tob_wgs_densify.py

In order to save space, I've repartitioned the final matrix table to 10 partitions.

Repartition matrix table to 10 partitions

---

scripts/hail_batch/variant_selection_exploration/main.py

phantomJS is a prerequisite for Bokeh plotting, so I added this into the `init` named argument within the main.py script.

Add phantomJS dependency

---

scripts/hail_batch/variant_selection/main.py

First test on a smaller number of workers.

Change from 50 to 20 primary workers

---

scripts/hail_batch/hgdp1kg_tobwgs_pca_pop_densified/README.md
scripts/hail_batch/hgdp1kg_tobwgs_pca_pop_densified/hgdp_1kg_tob_wgs_pop_pca_densified.py
scripts/hail_batch/hgdp1kg_tobwgs_pca_pop_densified/main.py

Perform PCA on NFE samples only after densifying and combining the HGDP/1kG + TOB-WGS samples.

Perform PCA on NFE samples 

---

scripts/plotting/hgdp_1kg_tob_wgs_pop_pca_densified_nfe/hgdp_1kg_tob_wgs_plot_pca_nfe.py

My previous script was plotting the PCA of values calculated from all samples, whereas now I'm only plotting a PCA from values calculated on NFE samples only. The output from this script was generated from `hgdp1kg_tobwgs_pca_pop_densified/hgdp_1kg_tob_wgs_pop_pca_densified.py`.

Plot PCA of NFE samples only

---

scripts/plotting/hgdp_1kg_tob_wgs_pop_pca_densified_nfe_loadings/README.md
scripts/plotting/hgdp_1kg_tob_wgs_pop_pca_densified_nfe_loadings/hgdp_1kg_tob_wgs_plot_loadings_nfe.py
scripts/plotting/hgdp_1kg_tob_wgs_pop_pca_densified_nfe_loadings/main.py

This script utilises the manhattan plot function from hail to plot the loadings from NFE samples from the combined HGDP/1kG + TOB-WGS dataset, after densifying. I could not use the original function, as it's intended for GWAS studies and displays the y-axis as a -log10 p-value.

Plot loadings of densified, NFE loadings

---

scripts/plotting/reprocessed_gatk4_samples_pca/README.md
scripts/plotting/reprocessed_gatk4_samples_pca/main.py
scripts/plotting/reprocessed_gatk4_samples_pca/project_reprocessed_gatk4_samples.py

I forgot to include phantomjs in the `hail_dataproc_job` (I should have tested this before). I've now tested the entire script on a small subset and it works fine. I've also updated the path in the README to be `cpg-tob-wgs-main-web` rather than `cpg-tob-wgs-web`.

Include phantomjs

---

scripts/plotting/reprocessed_gatk4_samples_pca/project_reprocessed_gatk4_samples.py

While the script itself works, I'm not able to tell how well the reprocessing pipeline worked, since I can't see what the samplenames are. I've now added this into the plot hoverfields.

Add samplenames in hover fields

---

scripts/hail_batch/nfe_loadings_qc/README.md
scripts/hail_batch/nfe_loadings_qc/main.py
scripts/hail_batch/nfe_loadings_qc/nfe_loadings_qc.py

I want to print out the frequency of the p-values in my `loadings.ht` file, since these are capping out my plot. This will help me decipher whether it's the actual p-value or my plotting script.

Loadings qc

---

scripts/plotting/reprocessed_kccg_samples_pca/README.md
scripts/plotting/reprocessed_kccg_samples_pca/main.py
scripts/plotting/reprocessed_kccg_samples_pca/project_reprocessed_kccg_samples.py

In addition to checking how well reprocessed samples match to the HGDP/1kG + TOB/WGS dataset using the GATK WARP pipeline, this script plots a PCA of samples which were reprocessed using the KCCG pipeline.

Plot PCA of samples reprocessed using the KCCG pipeline

---

scripts/hail_batch/nfe_loadings_qc/nfe_loadings_qc.py

Investigate a handful of variants which look like they're capped in the loadings plot.

Save mt of a handful of 'capped' variants

---

scripts/plotting/project_snp_chip_data/README.md
scripts/plotting/project_snp_chip_data/main.py
scripts/plotting/project_snp_chip_data/project_snp_chip_data.py

Project the TOB-WGS snp-chip data onto the HGDP/1kG + TOB-WGS PCA (on NFE samples only)

Test projecting snp-chip samples on hgdp/1kg data 

---

scripts/hail_batch/snp_chip_generate_pca/README.md
scripts/hail_batch/snp_chip_generate_pca/main.py
scripts/hail_batch/snp_chip_generate_pca/snp_chip_generate_pca.py

Test generating a PCA on TOB-WGS data that have been filtered to variants present in the SNP-chip data.

Test generating a PCA on TOB-WGS data

---

scripts/plotting/variant_selection_qc_histogram/README.md
scripts/plotting/variant_selection_qc_histogram/main.py
scripts/plotting/variant_selection_qc_histogram/variant_selection_qc_histogram.py

I want to know how many total variants I have from the output of my `variant_selection/hgdp_1kg_tob_wgs_variant_selection.py` script. In addition to printing out the total number of rows, I also plotted a histogram to see the total distribution of variants (including the cumulative distribution).

Plot histogram of allele frequency of newly-selected variants

---

scripts/plotting/hgdp_1kg_tob_wgs_pca_new_variants/README.md
scripts/plotting/hgdp_1kg_tob_wgs_pca_new_variants/main.py
scripts/plotting/hgdp_1kg_tob_wgs_pca_new_variants/plot_pca_and_loadings.py

Plot PCA and loadings of newly-selected variants, as per `variant_selection/hgdp_1kg_tob_wgs_variant_selection.py`

Plot pca new variants

---

scripts/plotting/hgdp_1kg_tob_wgs_pca_new_variants/plot_pca_and_loadings.py

I already have plots my study and continental population, but I'm seeing some strange clustering that is likely due to subpopulation. Having these extra exploratory plots would be handy.

Add additional plot on subpopulation

---

scripts/plotting/hgdp_1kg_tob_wgs_pop_pca_new_variants_nfe/README.md
scripts/plotting/hgdp_1kg_tob_wgs_pop_pca_new_variants_nfe/hgdp_1kg_tob_wgs_plot_pca_nfe.py
scripts/plotting/hgdp_1kg_tob_wgs_pop_pca_new_variants_nfe/main.py

Plot output from PCA for NFE samples, generated in `hgdp1kg_tobwgs_pca_pop_densified_new_variants/hgdp_1kg_tob_wgs_pop_pca_densified.py`.

Plot pca of nfe samples

---

scripts/hail_batch/hgdp1kg_tobwgs_pca_nfe_new_variants_no_outliers/README.md

Update outputdir path in README

---

scripts/plotting/hgdp_1kg_tob_wgs_pca_nfe_loadings_no_outliers/README.md
scripts/plotting/hgdp_1kg_tob_wgs_pca_nfe_loadings_no_outliers/hgdp_1kg_tob_wgs_plot_loadings_nfe_no_outliers.py
scripts/plotting/hgdp_1kg_tob_wgs_pca_nfe_loadings_no_outliers/main.py

This plots the loadings output from `hgdp1kg_tobwgs_pca_nfe_new_variants_no_outliers/hgdp_1kg_tob_wgs_nfe_pca_no_outliers.py`. This PCA was updated to remove all samples which are excluded from the gnomAD v3.1 release due to being related at the second degree or closer.

Plot loadings of NFE samples with all outliers removed

---

scripts/plotting/hgdp_1kg_tob_wgs_pca_new_variants_nfe_no_outliers/hgdp_1kg_tob_wgs_plot_pca_nfe.py
scripts/plotting/hgdp_1kg_tob_wgs_pca_nfe_loadings_no_outliers/hgdp_1kg_tob_wgs_plot_loadings_nfe_no_outliers.py

Plot new results from `hgdp1kg_tobwgs_pca_nfe_new_variants_no_outliers/hgdp_1kg_tob_wgs_nfe_pca_no_outliers.py`, which removed 3 outlier TOB NFE samples

Plot results PCA results after removing 3 outlier samples

---

scripts/hail_batch/king_tob_samples/README.md
scripts/hail_batch/king_tob_samples/king_nfe.py
scripts/hail_batch/king_tob_samples/king_tob.py
scripts/hail_batch/king_tob_samples/main.py

I want to see if any TOB samples come up as being related using the King estimate in order to help me understand outliers in the PCA.

Estimate king relatedness on TOB samples

---

scripts/plotting/hgdp1kg_tobwgs_pc_relate_unpruned/hgdp_1kg_tob_wgs_related_samples.py

Change version in pathname

---

scripts/plotting/hgdp1kg_tobwgs_pc_relate_unpruned/hgdp_1kg_tob_wgs_related_samples.py

Remove the step that filters related individuals

Plot unfiltered matrix

---

scripts/plotting/hgdp1kg_tobwgs_pc_relate_unpruned/README.md
scripts/plotting/hgdp1kg_tobwgs_pc_relate_unpruned/hgdp_1kg_tob_wgs_related_samples.py
scripts/plotting/hgdp1kg_tobwgs_pc_relate_unpruned/main.py

Export Hail tables as csv files into metadata bucket

Export csv files rather than html

---

scripts/hail_batch/af_tob_wgs/README.md
scripts/hail_batch/af_tob_wgs/calculate_maf.py
scripts/hail_batch/af_tob_wgs/main.py

Get number of variants with a MAF < 0.05 for TOB dataset.

Get number of variants with a MAF < 0.05

---

scripts/hail_batch/af_tob_wgs/calculate_maf.py

I want to test the `v5.1.mt` file (the file which includes reference blocks) in order to see if this changes the MAF

Test file which includes reference blocks

---

scripts/hail_batch/af_tob_wgs/README.md
scripts/hail_batch/af_tob_wgs/calculate_maf.py

As per this thread: https://centrepopgen.slack.com/archives/C01T0T41BHQ/p1633396557056900?thread_ts=1633382684.055700&cid=C01T0T41BHQ

Change relational operator when filtering for MAF

---

pyproject.toml
scripts/hail_batch/eqtl_hail_batch/README.md
scripts/hail_batch/eqtl_hail_batch/round2.conditional_analysis_test.py

@KatalinaBobowik, should we replace `scripts/hail_batch/eqtl_hail_batch/generate_eqtl_spearman.py` with `round2.conditional_analysis_test.py`? They look similar in my basic glance, and I've only iterated on the latter.
---
There were a lot of hard-coded file paths, so I've removed them in favour of passing them into a function, and creating a `click` command line, @KatalinaBobowik I've left you some <insert here> blanks in the help text to fill in. I haven't tested this yet, just wanted to get your initial thoughts, and maybe we can test together?
Here's an example of the help text:
```
python scripts/hail_batch/eqtl_hail_batch/round2.conditional_analysis_test.py --help
Usage: round2.conditional_analysis_test.py [OPTIONS]
Creates a Hail Batch pipeline for calculating EQTL using …
```

Parameterise inputs + add CLI

---

scripts/hail_batch/eqtl_hail_batch/generate_eqtl_spearman.py

@illusional I've tried to incorporate the click command into this first script, using a similar framework of what you did in `round2.conditional_analysis_test.py`. This is just a rough draft/skeleton of how I think it should look, but would love any feedback you might have.

Test parameterisation of first script

---

scripts/hail_batch/vep/main.py
scripts/hail_batch/vep/run_vep.py

Successfully completed in `test` [here](https://batch.hail.populationgenomics.org.au/batches/7651/jobs/2).

Update VEP version to v105

---

scripts/hail_batch/final_tob_batch_pca/README.md
scripts/hail_batch/final_tob_batch_pca/generate_pca_no_outliers.py

Remove `bucket_path` and replace with `dataset_path`. Successfully run on `test`: https://batch.hail.populationgenomics.org.au/batches/29630

Remove bucket path
